project: PROJECT_NAME
entity: ENTITY_NAME
method: grid
name: 'full_dist_linear'
metric: {'goal':'minimize', 'name':'valid_sem_err'}

# dataset description
SCORE_DATASET: 'datasets/unit_test_uncal_score.csv'
INDEX_DATASET: 'datasets/unit_test_hyp_idx.csv'
Hall: 12
num_of_classifiers: 3
D: 2
I: [2,3]
E: [3,2]
Hspaces: [0, 6, 6]
train_valid_test: [0.65, 0.15, 0.2]

# agent parameters
agent_type: "linear"
framework: "dist" #either dist or unif
epochs: 500
momentum: 0.6
batch_size: 200
lr: 0.001
# hidden_dims: 200

verbose_freq: 3