dataset_size: 2000
D: 2
I: [2,3]
E: [3,2]

# accuracies
d_acc: [0.92, 0.95]
i_acc: [0.95, 0.95]
e_acc: [0.90, 0.95]

# ECE (Expected Calibration Errors). Larger magnitudes -> Larger error
# Positive values are for overconfidence
# Negative values are for underconfidence
# ece = {'d1':-0.01}
d_ece: [-0.01 , -0.1]
i_ece: [-0.1  , 0.01]
e_ece: [0.1   , -0.1]

# PATHS for storing datasets
save-scores: "datasets/unit_test_uncal_score.csv"
save-idx: "datasets/unit_test_hyp_idx.csv"